[build-system]
requires = ["setuptools>=61", "wheel"]  # 61+ is plenty; latest is 80.9
build-backend = "setuptools.build_meta"

[project]
name = "yescrypt_hash"
version = "0.5"
description = "Binding for Yescrypt proof of work hashing."
requires-python = ">=3.8"